### ISSUE TITLE
Error in buffer increase

### ISSUE THREAD

**Issue by lhh-208** [godka/oboe-reproduce#2]
当我测试轨迹带宽为0的时候，缓冲区依然会增长，这就是不可能的事情
![image](https://user-images.githubusercontent.com/50354830/220000789-91243c28-8f78-406d-beaa-bcae718be649.png)
![image](https://user-images.githubusercontent.com/50354830/220000873-d828bae8-10b0-4401-a366-cad21dc954cd.png)

**Comment by godka** [comment]
网络轨迹的格式为[时间戳,带宽]，因此您截图的那个网络可以等价为1-8秒无网速。所以在下载第一个视频块的时候用了9秒多的时间，然后Oboe果断下调了档位，然而选最低码率之后还是卡了。于是它继续选了300kbps——这波操作看起来似乎很合理。

不过，我在生成configmap的时候也的确并没有考虑到超低带宽的情况，设置的最低带宽是0.5mbps。感谢提醒~

https://github.com/godka/oboe-reproduce/blob/71f395d425c8a0b3f0f29b2ef87f74814de10d6e/configmap/train_configmap.py#L91

考虑到这事儿问题也不大，我就暂时不改了：）

欢迎提交PR

**Comment by lhh-208** [comment]
问题在于，第一个rebuf高达9s，那么buffer-size应该为0才是，因此在第9s前，buffer-size都应该是0
![image](https://user-images.githubusercontent.com/50354830/220010791-98c4989d-ee43-4173-b8c3-a244bab030d7.png)

**Comment by lhh-208** [comment]
我明白了，logfile写入是当一个切片传输完成之后，并非是当前按照时间戳写入，所以如果想知道实际时间戳，还需要进行计算才行
